import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import LoginBtn from "./LoginBtn";
import { getServerSession } from "next-auth";
import { authOptions } from "@/pages/api/auth/[...nextauth]";
import LogoutBtn from "./LogoutBtn";
import { cookies } from "next/headers";
import Theme from "./Theme";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  let a = await getServerSession(authOptions);

  let res = cookies().get("mode");

  return (
    <html lang="en">
      <body className={res != undefined && res.value == "dark" ? "dark-mode" : ""}>
        <div className="navbar">
          <Link href="/" className="logo">
            ㅁㄴㅇㄹㅁㄹㅇ
          </Link>
          <Link href="/list">List</Link>
          {a ? (
            <span>
              {a.user.name}
              <LogoutBtn></LogoutBtn>
            </span>
          ) : (
            <LoginBtn></LoginBtn>
          )}
          <Theme></Theme>
        </div>
        {children}
      </body>
    </html>
  );
}
