import { Inter } from "next/font/google";
import "./globals.css";
import { getServerSession } from "next-auth";
import { authOptions } from "../pages/api/auth/[...nextauth]";
import { cookies } from "next/headers";
import "bootstrap/dist/css/bootstrap.min.css";
import NavBar from "./components/common/Navbar/Navbar";
import Footer from "./components/common/Footer/Footer";
// fontawesome error
// https://docs.fontawesome.com/web/use-with/react/use-with#next-js
import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
config.autoAddCss = false;

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions);
  const modeColor = cookies().get("mode");

  return (
    <html lang="en">
      <body className={modeColor != undefined && modeColor.value == "light" ? "light-mode" : "dark-mode"}>
        <NavBar session={session} modeColor={modeColor} />
        <div className="children">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
